application: oauth-privacy-email
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+ 
  script: handle_incoming_email.py
    
- url: .*
  script: main.py
